version: "2.4"
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "200k"
    max-file: "10"

services:
  v2ray:
    container_name: v2ray-c
    image: heapops/v2ray:latest
    volumes:
      - ./config.json:/etc/v2ray/config.json
    restart: unless-stopped
    env_file: ./v2ray.secret
    ports:
      - "${SOCKS5_PROXY_LISTEN:-127.0.0.1:1080}:1080/tcp"
      - "${HTTP_PROXY_LISTEN:-127.0.0.1:2080}:2080/tcp"
    network_mode: "bridge"
    logging: *default-logging
